### ISSUE TITLE
Error in AT

### ISSUE THREAD

**Issue by laiaquixalos** [cgkineo/adapt-graphicLottie#14]
### Subject of the issue/enhancement/features
Trying to make it work in my AT

### Your environment
data-adapt-framework-version="5.3.0"
data-adapt-authoring-version="0.10.3"
Versión 114.0.5735.90 (Build oficial) (64 bits)
Windows 10

### Steps to reproduce
First I could not install de plugin so I've changed in bower the version, and put "framework": ">=5", So now I've been able to install it. The problem is when I try the extension it appears this error, 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
<img width="524" alt="Captura de pantalla 2023-06-08 a las 17 06 05" src="https://github.com/cgkineo/adapt-graphicLottie/assets/5559138/f26e6a45-062b-46ca-bd67-7deb4143dccc">

### Screenshots (if you can)

**Comment by oliverfoster** [comment]
Upgrade your fw version https://github.com/cgkineo/adapt-graphicLottie/blob/599b482596331e5c3f2073165e7b89e5b77f0ca9/package.json#L4

5.14 is the minimum
